### PR TITLE
Mexican Spanish translation

### PR DESCRIPTION
**Pull request by TheLegendofSaram**
Just a simple Mexican Spanish translation

### CODE REVIEW

**Comment by Motschen** [comment]
Thanks :)
You might need to add a few new strings for Blur+, but I'm still going to include it in the initial version.

**Comment by TheLegendofSaram** [comment]
Is blur+ already out?

**Comment by Motschen** [comment]
Yes, I just released it. 
I think I'm going to publish another update soon that adds compatibility with NeoForged, I'll make sure to include any new translations.

**Comment by TheLegendofSaram** [comment]
I just made a PR for the Blur + translation

**Pull request merged**
